name: Test Changes

on:
    push:
        branches:
            - '*'

jobs:
    delete-old:
        name: Delete Prior Dev Release
        runs-on: ubuntu-latest
        env:
            DEV_RELEASE: 0.1.0
        permissions:
          contents: write
        steps:
            - name: Delete previous release and tag
              uses: dev-drprasad/delete-tag-and-release@v0.2.1
              with:
                delete_release: true # default: false
                tag_name: ${{ env.DEV_RELEASE }} # tag name to delete
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    create-new:
        needs: 
        - delete-old
        name: Recreate Dev Release
        runs-on: ubuntu-latest
        env:
            DEV_RELEASE: 0.1.0
        permissions:
          contents: write
        steps:
            - name: Create the release
              id: create_release
              # if: steps.sleep.outcome
              uses: komish/action-gh-release@consolelogging
              with:
                tag_name: ${{ env.DEV_RELEASE }}
                body: "Development release created with each merge into the main branch."
                prerelease: true
                draft: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}